elegant_prop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from core.views import HomeView, SamplePageView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^sample/$', SamplePageView.as_view(), name='sample'),

    # Property related urls.
    url(r'^property/', include('properties.urls')),

    # Transaction related urls.
    url(r'^transaction/', include('transactions.urls')),

    # Messenger related urls.
    url(r'^messenger/', include('messenger.urls')),
    
    url(r'^admin/', admin.site.urls),
]

messenger/urls.py
# messenger/urls.py

from django.conf.urls import url

from . import views

app_name = 'messenger'

urlpatterns = [
# E.g., http://localhost/messenger/list
    url(r'^list/$', views.MessageListView.as_view(), name='list'),
    url(r'^add/$', views.MessageCreateView.as_view(), name='add'),
]

properties/urls.py
# properties/urls.py

from django.conf.urls import url

from . import views

app_name = 'properties'

urlpatterns = [
    url(r'^$', views.PropertyListView.as_view(), name='list'),
    url(r'^add/$', views.PropertyCreateView.as_view(), name='add'),

# http://localhost:8000/property/edit/1/
    url(r'^edit/(?P<pk>[0-9]+)/$', views.PropertyUpdateView.as_view(), name='edit'),

# http://localhost:8000/property/1/
    url(r'^(?P<pk>[0-9]+)/$', views.PropertyDetailView.as_view(), name='detail'),
]

transactions/urls.py
# transactions/urls.py

from django.conf.urls import url

from . import views

app_name = 'transactions'

urlpatterns = [
    
# E.g., http://localhost:8000/transactions
    url(r'^list/(?P<prop_pk>[0-9]+)/$', views.TransactionListView.as_view(), name='list_by_prop'),

# E.g., http://localhost:8000/transactions/edit/1/
    url(r'^add/$', views.TransactionCreateView.as_view(), name='add'),

# E.g., http://localhost:8000/transactions/edit/1/
    url(r'^edit/(?P<pk>[0-9]+)/$', views.TransactionUpdateView.as_view(), name='edit'),

# E.g., http://localhost:8000/transactions/1/
    url(r'^(?P<pk>[0-9]+)/$', views.TransactionDetailView.as_view(), name='detail'),

    url(r'^search/$', views.TransactionSearchView.as_view(), name='search'),
]

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

messenger/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models



class Message(models.Model):
    """ Implement a model for the messenger app called __Message__ (messenger/
    models.py). This model has the following attributes: a subject line, the 
    message text, date created, and email of the person submitting the message.
    """
    subject = models.CharField(max_length=255)
    text = models.TextField()
    date_created = models.DateTimeField(auto_now=True)
    sender_email = models.EmailField()
    

properties/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Property(models.Model):
    prop_type = models.CharField(max_length=48)
    address = models.CharField(max_length=512, null=True)
    zip_code = models.IntegerField(null=True)
    description = models.TextField()
    picture_url = models.CharField(max_length=256)
    price = models.DecimalField(decimal_places=2, max_digits=10)   

    def __str__(self):
        return self.prop_type + ' @ ' + self.address

transactions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from properties.models import Property

TRANS_TYPES = (('offer', 'OFFER'), ('cancel', 'CANCEL OFFER'), ('close', 'CLOSE'))

class Transaction(models.Model):
    prop = models.ForeignKey(Property, related_name='transactions')
    trans_date = models.DateTimeField(auto_now=True)
    trans_type = models.CharField(max_length=64, choices=TRANS_TYPES)

messenger/forms.py
# forms.py

transactions/forms.py
# transactions/forms.py

from django import forms
from django.forms import Form

class TransactionLookupForm(Form):
    search_query = forms.CharField(widget=forms.TextInput, label="Search Transactions")

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = 'core/home.html'

class SamplePageView(generic.TemplateView):
    template_name = 'core/sample.html'

messenger/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .models import Message

class MessageListView(generic.ListView):
    """Add a way to display a list of all messages in the db in a html page."""
    model = Message
    template_name = "messenger/list.html"

class MessageCreateView(generic.CreateView):
    model = Message
    template_name = 'messenger/add.html'
    fields = ['subject', 'text', 'sender_email']
    success_url = reverse_lazy("messenger:list")

properties/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .models import Property


# Show the all the properties in the db.

class PropertyListView(generic.ListView):
    model = Property
    template_name = "properties/list.html"


class PropertyDetailView(generic.DetailView):
    model = Property
    template_name = "properties/detail.html"


class PropertyCreateView(generic.CreateView):
    model = Property  # what type of object we are creating?
    template_name = "properties/create.html"  # the page to display the form.
    fields = ['prop_type', 'address', 'zip_code', 'description', 'picture_url', 'price',]
    success_url = reverse_lazy('properties:list')


class PropertyUpdateView(generic.UpdateView):
    model = Property  # what type of object we are editing?
    template_name = "properties/edit.html"  # the page to display the form.
    fields = ['prop_type', 'address', 'zip_code', 'description', 'picture_url', 'price',]
    success_url = reverse_lazy('properties:list')

transactions/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .models import Transaction
from .forms import TransactionLookupForm

from properties.models import Property


class TransactionListView(generic.ListView):
    """Lists the transactions associated with a Transaction object. """

    model = Transaction
    template_name = 'transactions/list.html'

    def get_queryset(self, **kwargs):
        prop = self.kwargs.get('prop_pk')
        return Transaction.objects.filter(prop__pk=prop)

    def get_context_data(self, **kwargs):
        context = super(TransactionListView, self).get_context_data(**kwargs)
        
        context['prop'] = Property.objects.get(pk=self.kwargs.get('prop_pk'))
        
        return context


class TransactionDetailView(generic.DetailView):
    model = Transaction
    template_name = "transactions/detail.html"


class TransactionCreateView(generic.CreateView):
    model = Transaction  # what type of object we are creating?
    template_name = "transactions/create.html"  # the page to display the form.
    fields = ['prop', 'trans_type',]
    success_url = reverse_lazy('properties:list')


class TransactionUpdateView(generic.UpdateView):
    model = Transaction  # what type of object we are editing?
    template_name = "transactions/edit.html"  # the page to display the form.
    fields = ['prop', 'trans_type',]
    success_url = reverse_lazy('properties:list')


class TransactionSearchView(generic.FormView):
    template_name = "transactions/search.html"
    form_class = TransactionLookupForm

    def get_context_data(self, **kwargs):
        context = super(TransactionSearchView, self).get_context_data(**kwargs)
        
        # The GET query param might be null. Proceed silently to exception clause
        try:
            q = self.request.GET['search_query'] 
            transactions = Transaction.objects.all()
            results = []
            for i in transactions:
                if q in i.trans_type:
                    results.append(i)
            context['results'] = results
            context['report'] = True   
        except Exception as e:
            
            pass

        
        return context

core/templates/core/base.html
<!-- core/base.html -->
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'bootstrap-4.0.0/css/bootstrap.min.css' %}">

        <style type="text/css">
            body {
                background-image: url("{% static 'img/rolling-waves.jpg' %}")
            }
        </style>
        <title>{% block page_title %}Elegant Props{% endblock page_title %}</title>
    </head>

    <body>

        <!-- Outer container for any page that extends this template. -->
        <div class="container">
            <!-- Page heading block -->
            <div class="row">
                <div class="col-md-10 offset-md-1 text-center">
                    <h1>{% block page_header %}Page header goes here...{% endblock page_header %}</h1>
                </div>
            </div>

            <!-- Main content block -->
            <div class="row">
                <div class="col-md-10 offset-md-1">
                {% block content %}Probably want to put some content in this block.{% endblock content %}
                </div>
            </div>
        </div>
        
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'bootstrap-4.0.0/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

core/templates/core/home.html
<!-- core/home.html -->
{% extends "core/base.html" %}

{% block page_title %} Proper {% endblock page_title %}

{% block page_header %}Elegant Props: The Final Exam{% endblock page_header %}

{% block content %}
<div class="row home_row">
    <div class="col text-center">
        <p>Welcome to Elegant Props where you are always treated like royalty.</p>
        <h3><a href="{% url 'properties:list' %}">See our properties</h3></a>
        <h4><a href="{% url 'messenger:list' %}">View Messages</h4></a>
    </div>
</div>
{% endblock content %}

core/templates/core/sample.html
<!-- core/home.html -->
{% extends "core/base.html" %}

{% block page_title %} Proper {% endblock page_title %}

{% block page_header %}
<div class="row">
    <div class="col" style="background-color: pink;">
        <p>This is a <i>page_header</i> block.</p>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="row">
    <div class="col" style="background-color: gray;">
        <p>This is a <i>content</i> block.</p>
    </div>
</div>

{% endblock content %}

messenger/templates/messenger/add.html
<!-- messenger/add.html -->

{% extends "core/base.html" %}


{% block page_header %}
<div class="row">
    <div class="col">
        <p>Post a new message!</p>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="row">
    <div class="col">
        <form action="." method="post"> {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add It!"/>
        </form>
    </div>
</div>

{% endblock content %}

messenger/templates/messenger/list.html
<!-- messenger/list.html -->
{% extends "core/base.html" %}
{% load humanize %}

{% block page_title %} Elegant Messages {% endblock page_title %}

{% block page_header %}Elegant Messages{% endblock page_header %}

{% block content %}
<p>
    <a href="{% url 'properties:list' %}">Listings</a>
</p>


{% for message in object_list %}
<div class="row">
    <div class="col">
        <div class="card" >
            <div class="card-body">
                <h5 class="card-title">{{ message.subject }}</h5>
                <p class="card-subtitle">{{ message.text }}</p>
                <h6 class="card-text text-muted">{{ message.sender_email }}</h6>
                <p class="card-text">{{ message.date_created }}</p>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock content %}

properties/templates/properties/create.html
<!-- properties/create.html -->

{% extends "core/base.html" %}


{% block page_header %}
<div class="row">
    <div class="col">
        <p>Add a New Property!</p>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="row">
    <div class="col">
        <form action="." method="post"> {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add It!"/>
        </form>
    </div>
</div>

{% endblock content %}

properties/templates/properties/detail.html
<!-- properties/detail.html -->
{% extends "core/base.html" %}
{% load humanize %}

{% block page_title %} Property  {% endblock page_title %}

{% block page_header %}
<div class="row">
    <div class="col">
        <p>{{ object.prop_type }}</p>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="row">
    <div class="col">
        <p class="smaller"><a href="{% url 'properties:list' %}">back</a></p>
        <img src="{{ object.picture_url }}"/>
        <p>{{ object.address }}</p>
        <p>{{ object.zip_code }}</p>
        <p>$ {{ object.price }}</p>
        <p>{{ object.description }}</p>
    </div>
</div>

{% endblock content %}

properties/templates/properties/edit.html
<!-- properties/edit.html -->

{% extends "core/base.html" %}


{% block page_header %}
<div class="row">
    <div class="col">
        <p>Editing {{ object }}</p>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="row">
    <div class="col">
        <form action="." method="post"> {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save It!"/>
        </form>
    </div>
</div>

{% endblock content %}

properties/templates/properties/list.html
<!-- properties/list.html -->
{% extends "core/base.html" %}
{% load humanize %}

{% block page_title %} Proper {% endblock page_title %}

{% block page_header %}Our Properties{% endblock page_header %}

{% block content %}
<p>
        <a href="{% url 'properties:add' %}">Add a new listing</a>
    </p>
<div class="row">

{% for prop in object_list %}
    <div class="col">
        <div class="card" style="width: 24rem;">
            <div class="card-body">
                <img class="card-img-top" src="{{ prop.picture_url }}" alt="Card image cap">
                <h5 class="card-title">{{ prop.prop_type }}</h5>
                <p class="card-text">{{ prop.address }}</p>
                <h6 class="card-subtitle mb-2 text-muted">${{ prop.price|intcomma }}</h6>
                <p class="card-text">{{ prop.description }}</p>

                <a href="{% url 'properties:edit' prop.pk %}" class="card-link-bottom btn btn-default btn-sm">Edit</a>

                <a href="{% url 'properties:detail' prop.pk %}" class="card-link-bottom btn btn-default btn-sm">Check it out</a>

                <p><a href="{% url 'transactions:list_by_prop' prop.pk %}" class="card-link-bottom btn btn-default btn-sm">View Transactions</a></p>

            </div>
        </div>
    </div>
{% endfor %}
</div>

{% endblock content %}

transactions/templates/transactions/create.html
<!-- transactions/create.html -->

{% extends "core/base.html" %}


{% block page_header %}
<div class="row">
    <div class="col">
        <p>Add a New Transaction</p>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="row">
    <div class="col">
        <form action="." method="post"> {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add It!"/>
        </form>
    </div>
</div>

{% endblock content %}

transactions/templates/transactions/detail.html
<!-- transactions/detail.html -->
{% extends "core/base.html" %}
{% load humanize %}

{% block page_title %} Transaction Details  {% endblock page_title %}

{% block page_header %}
<div class="row">
    <div class="col">
        <p>Transactions for {{ object.prop }}</p>
        <p><img src="{{ object.prop.picture_url }}"/></p>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="row">
    <div class="col">
        <p class="smaller"><a href="{% url 'transactions:list_by_prop' object.prop.pk %}">back</a></p>
        <p>{{ object.trans_type }}</p>
        <p>{{ object.trans_date }}</p>
    </div>
</div>

{% endblock content %}

transactions/templates/transactions/edit.html
<!-- transactions/edit.html -->

{% extends "core/base.html" %}


{% block page_header %}
<div class="row">
    <div class="col">
        <p>Editing {{ object }}</p>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="row">
    <div class="col">
        <form action="." method="post"> {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save It!"/>
        </form>
    </div>
</div>

{% endblock content %}

transactions/templates/transactions/list.html
<!-- transactions/list.html -->
{% extends "core/base.html" %}

{% block page_title %} Proper {% endblock page_title %}

{% block page_header %}
<div class="row">
    <div class="col">
        Transactions for {{ prop }}
        <p><img src="{{ prop.picture_url }}" height="200px"/></p>
    </div>
</div>
{% endblock page_header %}

{% block content %}
    
    <p class="text-center">
        <a href="{% url 'transactions:add' %}" class="btn btn-sm btn-success">Add a new transaction</a> 
        <a href="{% url 'transactions:search' %}" class="btn btn-sm btn-warning">Search Transactions</a>
    </p>
    
    <hr>

    <ul class="list-unstyled">
    {% for transaction in object_list %}
        <li><p>
            <div class="row">
                <div class="col-md-1 small"> <a href="{% url 'transactions:detail' transaction.pk %}" class="btn btn-sm btn-primary">view</a> </div>
                <div class="col-md-1 small"> <a href="{% url 'transactions:edit' transaction.pk %}" class="btn btn-sm btn-warning">edit</a> </div>
                <div class="col-md-3 small">{{ transaction.trans_date }}</div>
                <div class="col small">{{ transaction.trans_type }}</div>
            </div>
        </p></li>
    {% empty %}
        No transactions have been created for this property.
    {% endfor %}
    </ul>
    
{% endblock content %}

transactions/templates/transactions/search.html
<!-- transactions/search.html -->

{% extends "core/base.html" %}
{% load static %}


{% block page_header %}
<div class="row">
    <div class="col">
        <p>Search Transactions</p>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="row">
    <div class="col-md-4">
        <form action="." method="get"> {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Search"/>
        </form>
    </div>
    <div class="col-md-8">
        {% if report %}
            {% for transaction in results %}
                <p>{{ transaction.prop }} - {{ transaction.trans_type }}</p>
            {% empty %}
                <p>No matching transactions found.</p>
                <p><img src="{% static 'img/lava.jpg' %}" width="100%"></p>
                
            {% endfor %}
        {% endif %}

    </div>
</div>

{% endblock content %}